/****************************************************************************

RickSynth
----------

MIT License

Copyright (c) [2021] [Richard Davies]

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
****************************************************************************/


#include "_vectors.h"

#include <stdint.h>

#include "_startup.h"


#define WEAK_REF_ATTRIBUTE    __attribute__((weak, alias("defaultHandler")))


/* generated by linker */
extern uint8_t _estack;


void defaultHandler(void)
{
}

void NMI_Handler        (void) WEAK_REF_ATTRIBUTE;
void HardFault_Handler  (void) WEAK_REF_ATTRIBUTE;
void MemManage_Handler  (void) WEAK_REF_ATTRIBUTE;
void BusFault_Handler   (void) WEAK_REF_ATTRIBUTE;
void UsageFault_Handler (void) WEAK_REF_ATTRIBUTE;
void SVC_Handler        (void) WEAK_REF_ATTRIBUTE;
void DebugMon_Handler   (void) WEAK_REF_ATTRIBUTE;
void PendSV_Handler     (void) WEAK_REF_ATTRIBUTE;
void SysTick_Handler    (void) WEAK_REF_ATTRIBUTE;

void WWDG_IRQHandler                  (void) WEAK_REF_ATTRIBUTE;
void PVD_IRQHandler                   (void) WEAK_REF_ATTRIBUTE;
void TAMP_STAMP_IRQHandler            (void) WEAK_REF_ATTRIBUTE;
void RTC_WKUP_IRQHandler              (void) WEAK_REF_ATTRIBUTE;
void FLASH_IRQHandler                 (void) WEAK_REF_ATTRIBUTE;
void RCC_IRQHandler                   (void) WEAK_REF_ATTRIBUTE;
void ADC_IRQHandler                   (void) WEAK_REF_ATTRIBUTE;
void TIM1_BRK_TIM9_IRQHandler         (void) WEAK_REF_ATTRIBUTE;
void TIM1_UP_TIM10_IRQHandler         (void) WEAK_REF_ATTRIBUTE;
void TIM1_TRG_COM_TIM11_IRQHandler    (void) WEAK_REF_ATTRIBUTE;
void TIM1_CC_IRQHandler               (void) WEAK_REF_ATTRIBUTE;
void TIM2_IRQHandler                  (void) WEAK_REF_ATTRIBUTE;
void TIM3_IRQHandler                  (void) WEAK_REF_ATTRIBUTE;
void TIM4_IRQHandler                  (void) WEAK_REF_ATTRIBUTE;
void USART1_IRQHandler                (void) WEAK_REF_ATTRIBUTE;
void USART2_IRQHandler                (void) WEAK_REF_ATTRIBUTE;
void RTC_Alarm_IRQHandler             (void) WEAK_REF_ATTRIBUTE;
void OTG_FS_WKUP_IRQHandler           (void) WEAK_REF_ATTRIBUTE;
void SDIO_IRQHandler                  (void) WEAK_REF_ATTRIBUTE;
void TIM5_IRQHandler                  (void) WEAK_REF_ATTRIBUTE;
void OTG_FS_IRQHandler                (void) WEAK_REF_ATTRIBUTE;
void USART6_IRQHandler                (void) WEAK_REF_ATTRIBUTE;
void FPU_IRQHandler                   (void) WEAK_REF_ATTRIBUTE;


void i2c_event_irq_handler            (void) WEAK_REF_ATTRIBUTE;
void i2c_error_irq_handler            (void) WEAK_REF_ATTRIBUTE;
void spi_irq_handler                  (void) WEAK_REF_ATTRIBUTE;
void io_ext_irq_handler               (void) WEAK_REF_ATTRIBUTE;
void dma_irq_hanlder                  (void) WEAK_REF_ATTRIBUTE;


irq_vector_t _vectors[] __attribute__ ((section(".irq_vectors"),used)) =
{
  (irq_vector_t)&_estack,         /*      Initial Stack Pointer     */
  start_resetHandler,             /*      Reset Handler             */
  NMI_Handler,                    /*      NMI Handler               */
  HardFault_Handler,              /*      Hard Fault Handler        */
  MemManage_Handler,              /*      MPU Fault Handler         */
  BusFault_Handler,               /*      Bus Fault Handler         */
  UsageFault_Handler,             /*      Usage Fault Handler       */
  0,                              /*      Reserved                  */
  0,                              /*      Reserved                  */
  0,                              /*      Reserved                  */
  0,                              /*      Reserved                  */
  SVC_Handler,                    /*      SVCall Handler            */
  DebugMon_Handler,               /*      Debug Monitor Handler     */
  0,                              /*      Reserved                  */
  PendSV_Handler,                 /*      PendSV Handler            */
  SysTick_Handler,                /*      SysTick Handler           */
  WWDG_IRQHandler,                /* Window WatchDog                */
  PVD_IRQHandler,                 /* PVD through EXTI Line          */
  TAMP_STAMP_IRQHandler,          /* Tamper & TimeStamps EXTI line  */
  RTC_WKUP_IRQHandler,            /* RTC Wakeup through  EXTI line  */
  FLASH_IRQHandler,               /* FLASH                          */
  RCC_IRQHandler,                 /* RCC                            */
  io_ext_irq_handler,             /* EXTI Line0                     */
  io_ext_irq_handler,             /* EXTI Line1                     */
  io_ext_irq_handler,             /* EXTI Line2                     */
  io_ext_irq_handler,             /* EXTI Line3                     */
  io_ext_irq_handler,             /* EXTI Line4                     */
  dma_irq_hanlder,                /* DMA1 Stream 0                  */
  dma_irq_hanlder,                /* DMA1 Stream 1                  */
  dma_irq_hanlder,                /* DMA1 Stream 2                  */
  dma_irq_hanlder,                /* DMA1 Stream 3                  */
  dma_irq_hanlder,                /* DMA1 Stream 4                  */
  dma_irq_hanlder,                /* DMA1 Stream 5                  */
  dma_irq_hanlder,                /* DMA1 Stream 6                  */
  ADC_IRQHandler,                 /* ADC1                           */
  0,                              /* Reserved                       */
  0,              	              /* Reserved                       */
  0,                              /* Reserved                       */
  0,                              /* Reserved                       */
  io_ext_irq_handler,             /* External Line[9:5]s            */
  TIM1_BRK_TIM9_IRQHandler,       /* TIM1 Break and TIM9            */
  TIM1_UP_TIM10_IRQHandler,       /* TIM1 Update and TIM10          */
  TIM1_TRG_COM_TIM11_IRQHandler,  /* TIM1 Trigger & Commutation & TIM11 */
  TIM1_CC_IRQHandler,             /* TIM1 Capture Compare         */
  TIM2_IRQHandler,                /* TIM2                         */
  TIM3_IRQHandler,                /* TIM3                         */
  TIM4_IRQHandler,                /* TIM4                         */
  i2c_event_irq_handler,          /* I2C1 Event                   */
  i2c_error_irq_handler,          /* I2C1 Error                   */
  i2c_event_irq_handler,          /* I2C2 Event                   */
  i2c_error_irq_handler,          /* I2C2 Error                   */
  spi_irq_handler,                /* SPI1                         */
  spi_irq_handler,                /* SPI2                         */
  USART1_IRQHandler,              /* USART1                       */
  USART2_IRQHandler,              /* USART2                       */
  0,                              /* Reserved                     */
  io_ext_irq_handler,             /* External Line[15:10]s        */
  RTC_Alarm_IRQHandler,           /* RTC Alarm (A and B) through EXTI Line */
  OTG_FS_WKUP_IRQHandler,         /* USB OTG FS Wakeup through EXTI line */
  0,                              /* Reserved     				        */
  0,                              /* Reserved       			        */
  0,                              /* Reserved 					          */
  0,                              /* Reserved                     */
  dma_irq_hanlder,                /* DMA1 Stream7                 */
  0,                              /* Reserved                     */
  SDIO_IRQHandler,                /* SDIO                         */
  TIM5_IRQHandler,                /* TIM5                         */
  spi_irq_handler,                /* SPI3                         */
  0,                              /* Reserved                     */
  0,                              /* Reserved                     */
  0,                              /* Reserved                     */
  0,                              /* Reserved                     */
  dma_irq_hanlder,                /* DMA2 Stream 0                */
  dma_irq_hanlder,                /* DMA2 Stream 1                */
  dma_irq_hanlder,                /* DMA2 Stream 2                */
  dma_irq_hanlder,                /* DMA2 Stream 3                */
  dma_irq_hanlder,                /* DMA2 Stream 4                */
  0,                    			    /* Reserved                     */
  0,              					      /* Reserved                     */
  0,              					      /* Reserved                     */
  0,             					        /* Reserved                     */
  0,              					      /* Reserved                     */
  0,              					      /* Reserved                     */
  OTG_FS_IRQHandler,              /* USB OTG FS                   */
  dma_irq_hanlder,                /* DMA2 Stream 5                */
  dma_irq_hanlder,                /* DMA2 Stream 6                */
  dma_irq_hanlder,                /* DMA2 Stream 7                */
  USART6_IRQHandler,              /* USART6                       */
  i2c_event_irq_handler,          /* I2C3 event                   */
  i2c_error_irq_handler,          /* I2C3 error                   */
  0,                              /* Reserved                     */
  0,                              /* Reserved                     */
  0,                              /* Reserved                     */
  0,                              /* Reserved                     */
  0,                              /* Reserved                     */
  0,                              /* Reserved                     */
  0,                              /* Reserved                     */
  FPU_IRQHandler,                 /* FPU                          */
  0,                              /* Reserved                     */
  0,                              /* Reserved                     */
  spi_irq_handler,                /* SPI4                         */
};
