/****************************************************************************

RickSynth
----------

MIT License

Copyright (c) [2021] [Richard Davies]

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
****************************************************************************/


#include "wm8731.h"

#include "config_board.h"


/* --------WM8731_REG_LEFT_LINE_IN : (Offset: 0x00) Left Line in Control -------- */
#define WM8731_REG_LEFT_LINE_IN (0x00u)
#define WM8731_REG_LEFT_LINE_IN_LINVOL_POS 0
#define WM8731_REG_LEFT_LINE_IN_LINVOL_MSK (0x1fu << WM8731_REG_LEFT_LINE_IN_LINVOL_POS)
#define WM8731_REG_LEFT_LINE_IN_LINVOL(value) ((WM8731_REG_LEFT_LINE_IN_LINVOL_MSK & ((value) << WM8731_REG_LEFT_LINE_IN_LINVOL_POS)))
#define WM8731_REG_LEFT_LINE_IN_LINMUTE (0x1u << 7)
#define WM8731_REG_LEFT_LINE_IN_LRINBOTH (0x1u << 8)
/* --------WM8731_REG_RIGHT_LINE_IN : (Offset: 0x01) Right Line in Control -------- */
#define WM8731_REG_RIGHT_LINE_IN (0x01u)
#define WM8731_REG_RIGHT_LINE_IN_RINVOL_POS 0
#define WM8731_REG_RIGHT_LINE_IN_RINVOL_MSK (0x1fu << WM8731_REG_RIGHT_LINE_IN_RINVOL_POS)
#define WM8731_REG_RIGHT_LINE_IN_RINVOL(value) ((WM8731_REG_RIGHT_LINE_IN_RINVOL_MSK & ((value) << WM8731_REG_RIGHT_LINE_IN_RINVOL_POS)))
#define WM8731_REG_RIGHT_LINE_IN_RINMUTE (0x1u << 7)
#define WM8731_REG_RIGHT_LINE_IN_RLINBOTH (0x1u << 8)
/* --------WM8731_REG_LEFT_HEADPHONE_OUT : (Offset: 0x02) Left Headphone out Control -------- */
#define WM8731_REG_LEFT_HEADPHONE_OUT (0x02u)
#define WM8731_REG_LEFT_HEADPHONE_OUT_LHPVOL_POS 0
#define WM8731_REG_LEFT_HEADPHONE_OUT_LHPVOL_MSK (0x7fu << WM8731_REG_LEFT_HEADPHONE_OUT_LHPVOL_POS)
#define WM8731_REG_LEFT_HEADPHONE_OUT_LHPVOL(value) ((WM8731_REG_LEFT_HEADPHONE_OUT_LHPVOL_MSK & ((value) << WM8731_REG_LEFT_HEADPHONE_OUT_LHPVOL_POS)))
#define WM8731_REG_LEFT_HEADPHONE_OUT_LZCEN (0x1u << 7)
#define WM8731_REG_LEFT_HEADPHONE_OUT_LRHPBOTH (0x1u << 8)
/* --------WM8731_REG_RIGHT_HEADPHONE_OUT : (Offset: 0x03) Right Headphone out Control -------- */
#define WM8731_REG_RIGHT_HEADPHONE_OUT (0x03u)
#define WM8731_REG_RIGHT_HEADPHONE_OUT_RHPVOL_POS 0
#define WM8731_REG_RIGHT_HEADPHONE_OUT_RHPVOL_MSK (0x7fu << WM8731_REG_RIGHT_HEADPHONE_OUT_RHPVOL_POS)
#define WM8731_REG_RIGHT_HEADPHONE_OUT_RHPVOL(value) ((WM8731_REG_RIGHT_HEADPHONE_OUT_RHPVOL_MSK & ((value) << WM8731_REG_RIGHT_HEADPHONE_OUT_RHPVOL_POS)))
#define WM8731_REG_RIGHT_HEADPHONE_OUT_RZCEN (0x1u << 7)
#define WM8731_REG_RIGHT_HEADPHONE_OUT_RLHPBOTH (0x1u << 8)
/* --------WM8731_REG_ANALOGUE_AUDIO_PATH_CONTROL : (Offset: 0x04) Analogue Audio Path Control -------- */
#define WM8731_REG_ANALOGUE_AUDIO_PATH_CONTROL (0x04u)
#define WM8731_REG_ANALOGUE_AUDIO_PATH_CONTROL_MICBOOST (0x1u << 0)
#define WM8731_REG_ANALOGUE_AUDIO_PATH_CONTROL_MUTEMIC (0x1u << 1)
#define WM8731_REG_ANALOGUE_AUDIO_PATH_CONTROL_INSEL_MIC (0x1u << 2)
#define WM8731_REG_ANALOGUE_AUDIO_PATH_CONTROL_BYPASS (0x1u << 3)
#define WM8731_REG_ANALOGUE_AUDIO_PATH_CONTROL_DACSEL (0x1u << 4)
#define WM8731_REG_ANALOGUE_AUDIO_PATH_CONTROL_SIDETONE (0x1u << 5)
#define WM8731_REG_ANALOGUE_AUDIO_PATH_CONTROL_SIDETONE_ATTENUATION_POS 6
#define WM8731_REG_ANALOGUE_AUDIO_PATH_CONTROL_SIDETONE_ATTENUATION_MSK (0x3u << WM8731_REG_ANALOGUE_AUDIO_PATH_CONTROL_SIDETONE_ATTENUATION_POS)
#define WM8731_REG_ANALOGUE_AUDIO_PATH_CONTROL_SIDETONE_ATTENUATION(value) ((WM8731_REG_ANALOGUE_AUDIO_PATH_CONTROL_SIDETONE_ATTENUATION_MSK & ((value) << WM8731_REG_ANALOGUE_AUDIO_PATH_CONTROL_SIDETONE_ATTENUATION_POS)))
/* --------WM8731_REG_DIGITAL_AUDIO_PATH_CONTROL : (Offset: 0x05) Digital Audio Path Control -------- */
#define WM8731_REG_DIGITAL_AUDIO_PATH_CONTROL (0x05u)
#define WM8731_REG_DIGITAL_AUDIO_PATH_CONTROL_ADCHPD (0x1u << 0)
#define WM8731_REG_DIGITAL_AUDIO_PATH_CONTROL_DEEMP_DISABLE (0x0u << 1)
#define WM8731_REG_DIGITAL_AUDIO_PATH_CONTROL_DEEMP_32K (0x1u << 1)
#define WM8731_REG_DIGITAL_AUDIO_PATH_CONTROL_DEEMP_44_1K (0x2u << 1)
#define WM8731_REG_DIGITAL_AUDIO_PATH_CONTROL_DEEMP_48K (0x3u << 1)
#define WM8731_REG_DIGITAL_AUDIO_PATH_CONTROL_DACMU (0x1u << 3)
#define WM8731_REG_DIGITAL_AUDIO_PATH_CONTROL_HPOR (0x1u << 4)
/* --------WM8731_REG_POWER_DOWN_CONTROL : (Offset: 0x06) Power Down Control -------- */
#define WM8731_REG_POWER_DOWN_CONTROL (0x06u)
#define WM8731_REG_POWER_DOWN_CONTROL_LINEINPD (0x1u << 0)
#define WM8731_REG_POWER_DOWN_CONTROL_MICPD (0x1u << 1)
#define WM8731_REG_POWER_DOWN_CONTROL_ADCPD (0x1u << 2)
#define WM8731_REG_POWER_DOWN_CONTROL_DACPD (0x1u << 3)
#define WM8731_REG_POWER_DOWN_CONTROL_OUTPD (0x1u << 4)
#define WM8731_REG_POWER_DOWN_CONTROL_OSCPD (0x1u << 5)
#define WM8731_REG_POWER_DOWN_CONTROL_CLKOUTPD (0x1u << 6)
#define WM8731_REG_POWER_DOWN_CONTROL_POWEROFF (0x1u << 7)
/* --------WM8731_REG_DIGITAL_AUDIO_INTERFACE_FORMAT : (Offset: 0x07) Digital Audio Interface Control -------- */
#define WM8731_REG_DIGITAL_AUDIO_INTERFACE_FORMAT (0x07u)
#define WM8731_REG_DIGITAL_AUDIO_INTERFACE_FORMAT_MSB_RIGHT_JUSTIFIED (0x0u << 0)
#define WM8731_REG_DIGITAL_AUDIO_INTERFACE_FORMAT_MSB_LEFT_JUSTIFIED (0x1u << 0)
#define WM8731_REG_DIGITAL_AUDIO_INTERFACE_FORMAT_I2S (0x2u << 0)
#define WM8731_REG_DIGITAL_AUDIO_INTERFACE_FORMAT_DSP (0x3u << 0)
#define WM8731_REG_DIGITAL_AUDIO_INTERFACE_FORMAT_IWL_16_BIT (0x0u << 2)
#define WM8731_REG_DIGITAL_AUDIO_INTERFACE_FORMAT_IWL_20_BIT (0x1u << 2)
#define WM8731_REG_DIGITAL_AUDIO_INTERFACE_FORMAT_IWL_24_BIT (0x2u << 2)
#define WM8731_REG_DIGITAL_AUDIO_INTERFACE_FORMAT_IWL_32_BIT (0x3u << 2)
#define WM8731_REG_DIGITAL_AUDIO_INTERFACE_FORMAT_LRP (0x1u << 4)
#define WM8731_REG_DIGITAL_AUDIO_INTERFACE_FORMAT_LRSWAP (0x1u << 5)
#define WM8731_REG_DIGITAL_AUDIO_INTERFACE_FORMAT_MS (0x1u << 6)
#define WM8731_REG_DIGITAL_AUDIO_INTERFACE_FORMAT_BCLKINV (0x1u << 7)
/* --------WM8731_REG_SAMPLING_CONTROL : (Offset: 0x08) Sampling Control -------- */
#define WM8731_REG_SAMPLING_CONTROL (0x08u)
#define WM8731_REG_SAMPLING_CONTROL_USB_MODE (0x1u << 0)
#define WM8731_REG_SAMPLING_CONTROL_BOSR (0x1u << 1)
#define WM8731_REG_SAMPLING_CONTROL_SR_POS 2
#define WM8731_REG_SAMPLING_CONTROL_SR_MSK (0xf << WM8731_REG_SAMPLING_CONTROL_SR_POS)
#define WM8731_REG_SAMPLING_CONTROL_SR(value) ((WM8731_REG_SAMPLING_CONTROL_SR_MSK & ((value) << WM8731_REG_SAMPLING_CONTROL_SR_POS)))
#define WM8731_REG_SAMPLING_CONTROL_CLKIDIV2 (0x1u << 6)
#define WM8731_REG_SAMPLING_CONTROL_CLKODIV2 (0x1u << 7)
/* --------WM8731_REG_ACTIVE_CONTROL : (Offset: 0x09) Active Control -------- */
#define WM8731_REG_ACTIVE_CONTROL (0x09u)
#define WM8731_REG_ACTIVE_CONTROL_ACTIVE (0x1u << 0)
/* --------WM8731_REG_RESET : (Offset: 0x09) Reset Control -------- */
#define WM8731_REG_RESET (0x0Fu)
#define WM8731_REG_RESET_VALUE_POS 0
#define WM8731_REG_RESET_VALUE_MSK (0x1ffu << WM8731_REG_RESET_VALUE_POS)
#define WM8731_REG_RESET_VALUE(value) ((WM8731_REG_RESET_VALUE_MSK & ((value) << WM8731_REG_RESET_VALUE_POS)))


